namespace AgentStudio.Shared;

public record TaskDetail
{
    public TaskInfo Info { get; init; } = new();
    public string? PromptMarkdown { get; init; }
    /// <summary>
    /// Server-authored preprocessing audit for the prompt most recently
    /// materialized before dispatch. Null before the first preprocessing run.
    /// </summary>
    public PromptEnrichmentReport? EnrichmentReport { get; init; }
    /// <summary>
    /// Append-only timeline of task extensions: <c>prompt-1.md</c>,
    /// <c>prompt-2.md</c>, ... written by Extend mode. Empty when the user
    /// has never extended the task. Read in the order the timeline was
    /// written; the original task body is in <see cref="PromptMarkdown"/>.
    /// </summary>
    public List<TaskPromptHistoryEntry> PromptHistory { get; init; } = [];
    /// <summary>
    /// Append-only timeline of title changes recorded for this task in
    /// <c>title-history.json</c>. Each rename through
    /// <c>PUT /api/tasks/{id}/title</c> appends one entry; the current
    /// title stays on <see cref="TaskInfo.Title"/>. Empty when the title
    /// was never edited, including for legacy job folders that predate
    /// the file. Oldest first.
    /// </summary>
    public List<TaskTitleHistoryEntry> TitleHistory { get; init; } = [];
    public string? StatusMarkdown { get; init; }
    /// <summary>Producer metadata for <see cref="StatusMarkdown"/> when status.md was generated by the runner.</summary>
    public FileGenerationMeta? StatusGeneration { get; init; }
    public ContextUsageSnapshot? ContextUsage { get; init; }
    public List<TaskLogEntry> Log { get; init; } = [];
    public TaskSummaryState? SummaryState { get; init; }
    /// <summary>
    /// Task-level review evidence parsed from
    /// <c>results/review-evidence.jsonl</c>. Findings produced by security
    /// audits, code-review passes, task checks, or human reviewer notes.
    /// Empty when the file is absent or only contained malformed lines.
    /// Findings are evidence for review, not blockers: their presence does
    /// not gate any state transition. See
    /// <c>docs/system/contracts/filesystem.md</c> "results/review-evidence.jsonl".
    /// </summary>
    public List<ReviewEvidenceEntry> ReviewEvidence { get; init; } = [];

    /// <summary>
    /// The card's single review head, derived from the canonical
    /// <c>review-round-*.json</c> records written by both review planes. Every
    /// review surface reads this and only this, so the escalation banner, the
    /// Evidence tab, the Result header and the board chip cannot disagree about
    /// how many rounds ran, what blocked, and what to do next (AGT-2717).
    /// Also served on its own as <c>GET /api/tasks/{jobId}/review-projection</c>.
    /// Null only when the detail was assembled without the projection service.
    /// </summary>
    public AgentStudio.Review.ReviewProjection? ReviewProjection { get; init; }
}

/// <summary>
/// One finding in <c>results/review-evidence.jsonl</c>. The wire shape mirrors
/// the on-disk shape one-to-one so a producer can write the same record it
/// reads back. The producer is responsible for stable <see cref="Id"/> values
/// across appends so readers can fold the file into latest-per-id.
/// </summary>
public record ReviewEvidenceEntry
{
    public string Id { get; init; } = "";
    /// <summary>One of <see cref="ReviewEvidenceSources"/>. Unknown values are normalized to <c>other</c>.</summary>
    public string Source { get; init; } = ReviewEvidenceSources.Other;
    /// <summary>One of <see cref="ReviewEvidenceSeverities"/>. Unknown values are normalized to <c>info</c>.</summary>
    public string Severity { get; init; } = ReviewEvidenceSeverities.Info;
    public string Title { get; init; } = "";
    /// <summary>
    /// Stable producer-owned rule id, for example <c>QS-NG-002</c>. Null for
    /// narrative evidence that is not tied to a named rule.
    /// </summary>
    public string? RuleId { get; init; }
    public string? Body { get; init; }
    public DateTime CreatedAt { get; init; }
    /// <summary>1-based run index this finding belongs to (matches <c>RunRecord.Index</c>). Null when not tied to a specific run.</summary>
    public int? RunIndex { get; init; }
    /// <summary>Paths relative to the job folder, e.g. <c>results/foo.png</c>.</summary>
    public List<string> Artifacts { get; init; } = [];
    /// <summary>Repository-relative file references, optionally <c>path:line</c>.</summary>
    public List<string> FileRefs { get; init; } = [];
    public bool Acknowledged { get; init; }
    /// <summary>Job id of a queued follow-up created from this finding (set by the "Create follow-up task" action).</summary>
    public string? FollowupJobId { get; init; }
}

/// <summary>
/// Allowed source slugs on <see cref="ReviewEvidenceEntry.Source"/>.
/// Producers should write one of these literals. Unknown values are accepted
/// on read and normalised to <see cref="Other"/> so a malformed file never
/// breaks the endpoint.
/// </summary>
public static class ReviewEvidenceSources
{
    public const string SecurityAudit = "security-audit";
    public const string CodeReview = "code-review";
    public const string TaskCheck = "task-check";
    public const string HumanNote = "human-note";
    public const string Other = "other";

    public static readonly string[] All = [SecurityAudit, CodeReview, TaskCheck, HumanNote, Other];

    public static string Normalize(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return Other;
        var v = value.Trim();
        foreach (var s in All)
            if (string.Equals(s, v, StringComparison.OrdinalIgnoreCase)) return s;
        return Other;
    }
}

/// <summary>
/// Allowed severities on <see cref="ReviewEvidenceEntry.Severity"/>. Same
/// permissive-on-read contract as <see cref="ReviewEvidenceSources"/>.
/// </summary>
public static class ReviewEvidenceSeverities
{
    public const string Info = "info";
    public const string Warn = "warn";
    public const string High = "high";

    public static readonly string[] All = [Info, Warn, High];

    public static string Normalize(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return Info;
        var v = value.Trim();
        foreach (var s in All)
            if (string.Equals(s, v, StringComparison.OrdinalIgnoreCase)) return s;
        return Info;
    }
}

/// <summary>
/// One entry in the task's prompt-extension timeline. Index matches the
/// filename suffix (<c>prompt-3.md</c> → Index = 3).
/// </summary>
public record TaskPromptHistoryEntry
{
    public int Index { get; init; }
    public string FileName { get; init; } = "";
    public string Markdown { get; init; } = "";
    public DateTime WrittenAt { get; init; }
}

/// <summary>
/// One entry in the task's title-revision timeline. Written by
/// <see cref="AgentStudio.Tasks.TaskMutationService.SetJobTitle"/>
/// to <c>title-history.json</c> in the job folder whenever the title
/// actually changes (no-op renames are not recorded). The current title
/// stays on <see cref="TaskInfo.Title"/>; this is the audit trail of what
/// it used to be.
/// </summary>
public record TaskTitleHistoryEntry
{
    public DateTime At { get; init; }
    public string OldTitle { get; init; } = "";
    public string NewTitle { get; init; } = "";
    /// <summary>
    /// Free-form provenance label. Today the only writer is the rename
    /// endpoint and emits <c>"api"</c>; future producers (intake
    /// refinement, orchestrator) may use distinct sources so the UI can
    /// disambiguate.
    /// </summary>
    public string Source { get; init; } = "api";
}

public enum TaskSummaryStatus
{
    None,
    Generating,
    Ready,
    Failed,
    Degraded
}

public record TaskSummaryState
{
    public TaskSummaryStatus Status { get; init; } = TaskSummaryStatus.None;
    public DateTime? StartedAt { get; init; }
    public DateTime? FinishedAt { get; init; }
    public string? ErrorMessage { get; init; }
    public int? BytesWritten { get; init; }
    public int? Attempt { get; init; }
    public int? MaxAttempts { get; init; }
}

public record ContextUsageSnapshot
{
    public DateTime At { get; init; }
    public string Command { get; init; } = "/context usage";
    public string Status { get; init; } = "ok";
    public string? Error { get; init; }
    public List<ContextUsageMetric> Metrics { get; init; } = [];
    public List<ContextUsageSection> Sections { get; init; } = [];
    public List<string> Notes { get; init; } = [];
    public string RawText { get; init; } = "";
}

public record ContextUsageMetric
{
    public string Label { get; init; } = "";
    public string Value { get; init; } = "";
}

public record ContextUsageSection
{
    public string Title { get; init; } = "";
    public List<string> Items { get; init; } = [];
}

public record TaskLogEntry
{
    public DateTime Timestamp { get; init; }
    public string Event { get; init; } = "";
    public string? Detail { get; init; }
}

/// <summary>
/// Kind classification for a job-folder document artifact, used by
/// <c>GET /api/tasks/{id}/artifacts</c>. The frontend Files tab styles each
/// card by kind (prompt is editable; aspect carries the auto-review verdict
/// section; note marks operator/recovery hand-offs).
/// </summary>
public enum TaskArtifactKind
{
    Prompt,
    Aspect,
    CodeReview,
    Note,
    Other,
}

/// <summary>
/// Provenance for a generated Markdown file. Stored once in
/// <c>.metadata/files.json</c> when a producer writes the file, and merged into
/// file-list responses so consumers do not re-parse transcripts for every
/// render.
/// </summary>
public record FileGenerationMeta
{
    public string File { get; init; } = "";
    public string Kind { get; init; } = "";
    public string? Model { get; init; }
    public string? Cli { get; init; }
    public long TokensIn { get; init; }
    public long TokensOut { get; init; }
    public long CacheReadTokens { get; init; }
    public long CacheCreationTokens { get; init; }
    public long TokensTotal { get; init; }
    public DateTime? StartedAt { get; init; }
    public DateTime? EndedAt { get; init; }
    public long DurationMs { get; init; }
    public int? RunIndex { get; init; }
    public string? StepId { get; init; }
    public string? HeadShaAfter { get; init; }
}

/// <summary>
/// One supported document in the job root surfaced by the Files tab. The
/// content is not embedded; the existing
/// <c>GET /api/tasks/{id}/files/{fileName}</c> endpoint serves it on
/// demand so the listing stays cheap.
/// </summary>
public record TaskArtifact
{
    public string Name { get; init; } = "";
    public long SizeBytes { get; init; }
    public DateTime Mtime { get; init; }
    public TaskArtifactKind Kind { get; init; }
    /// <summary>Set when <see cref="Kind"/> is <c>Aspect</c>; the part between <c>aspect-</c> and <c>.md</c>.</summary>
    public string? AspectName { get; init; }
    /// <summary>Producer metadata when the file was generated by a runner / post-step.</summary>
    public FileGenerationMeta? Generation { get; init; }
}

/// <summary>Wire shape for <c>GET /api/tasks/{id}/artifacts</c>.</summary>
public record TaskArtifactsResponse
{
    public string JobId { get; init; } = "";
    public List<TaskArtifact> Files { get; init; } = [];
}
