namespace AgentStudio.Setup;

internal sealed class DemoInstaller(ProcessRunner processes, bool dryRun)
{
    public async Task InstallAsync(
        string releaseVersion,
        int port,
        CancellationToken cancellationToken)
    {
        var dataRoot = DemoRoot();
        var composePath = Path.Combine(dataRoot, "compose.yaml");
        var imagePrefix = Environment.GetEnvironmentVariable("AGENT_STUDIO_DEMO_IMAGE_PREFIX")
                          ?? "ghcr.io/agent-orc";
        var compose = BuildCompose(releaseVersion, port, imagePrefix);

        Console.WriteLine();
        Console.WriteLine("DEMO ONLY");
        Console.WriteLine("This path starts an isolated board with Docker.");
        Console.WriteLine("It mounts no source repositories and installs no execution host.");
        if (dryRun)
        {
            Console.WriteLine($"[dry-run] write {composePath}");
        }
        else
        {
            Directory.CreateDirectory(dataRoot);
            await File.WriteAllTextAsync(composePath, compose, cancellationToken);
        }

        await processes.RequireAsync(
            "docker",
            ["compose", "-f", composePath, "pull"],
            cancellationToken: cancellationToken);
        await processes.RequireAsync(
            "docker",
            ["compose", "-f", composePath, "up", "-d", "--wait"],
            cancellationToken: cancellationToken);

        Console.WriteLine();
        Console.WriteLine($"Demo board: http://localhost:{port}");
        Console.WriteLine($"Stop it with: docker compose -f {composePath} down");
        Console.WriteLine(
            "The demo is for viewing the product. Use the single-machine or multi-machine path to work on repositories.");
    }

    internal static string BuildCompose(string version, int port, string imagePrefix)
    {
        _ = SetupOptions.NormalizeVersion(version)
            ?? throw new ArgumentException("Demo image version is required.");
        if (port is < 1 or > 65535)
            throw new ArgumentException("Demo port must be between 1 and 65535.");
        if (!imagePrefix.StartsWith("ghcr.io/", StringComparison.Ordinal)
            || imagePrefix.Any(char.IsWhiteSpace))
            throw new ArgumentException("Demo image prefix must be a ghcr.io path.");
        return $"""
            # Generated by agent-orchestrator-setup. Demo only: no host repository is mounted.
            name: agent-studio-demo
            services:
              orchestrator-api:
                image: {imagePrefix}/agent-studio-api:v{version}
                restart: unless-stopped
                environment:
                  TaskRepository: /data/workspace
                  Runner__Role: test-subject
                volumes:
                  - demo-workspace:/data/workspace
                  - demo-projects:/data/projects

              frontend:
                image: {imagePrefix}/agent-studio-web:v{version}
                restart: unless-stopped
                depends_on:
                  - orchestrator-api
                ports:
                  # 8080 in the container: the web image runs Caddy unprivileged.
                  - "127.0.0.1:{port}:8080"

            volumes:
              demo-workspace:
              demo-projects:

            """;
    }

    private static string DemoRoot()
    {
        var dataHome = Environment.GetEnvironmentVariable("XDG_DATA_HOME");
        if (string.IsNullOrWhiteSpace(dataHome))
        {
            var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            if (string.IsNullOrWhiteSpace(home))
                throw new InvalidOperationException(
                    "Cannot resolve a user data directory for the demo compose file.");
            dataHome = Path.Combine(home, ".local", "share");
        }
        return Path.Combine(dataHome, "agent-studio", "demo");
    }
}
